# Generated by Django 3.1.7 on 2021-04-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='прочее', max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='stickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='sticker_img', verbose_name='Картинка стикера')),
                ('title', models.CharField(default='placeholder', max_length=100, verbose_name='Название стикерпака')),
                ('desc', models.CharField(default='placeholder', max_length=100, verbose_name='Описание стикерпака')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('slug', models.SlugField(unique=True, verbose_name='Короткое название для ссылки')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Стикер',
                'verbose_name_plural': 'Стикеры',
            },
        ),
    ]
