# Generated by Django 3.1.7 on 2021-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210415_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickers',
            name='keywords',
            field=models.CharField(default='sticker', max_length=255, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='stickers',
            name='desc',
            field=models.TextField(default='placeholder', verbose_name='Описание стикерпака'),
        ),
        migrations.AlterField(
            model_name='stickers',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Короткое название для ссылки'),
        ),
    ]
